### PR TITLE
Upgrading gradlew

### PR DESCRIPTION
**Pull request by JanBobolz**

### CODE REVIEW

**Comment by feidens** [comment]
why was this merged into main?

**Comment by rheitjoh** [comment]
main was the only branch that existed at the time. I only recently added a develop branch.

**Comment by feidens** [comment]
On origin there is no develop branch. Do you have something to push?

**Comment by rheitjoh** [comment]
Sorry, I confused Predenc with Groupsig. In that case we still need to create a develop branch.

**Pull request merged**
